name: Validate Pull Request
on:
  - pull_request
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile Source
        run: sh .actions/validate-pull-request.sh